"use client";
import Link from "next/link";
import { CheckCircle2Icon, PlaneIcon, SearchIcon } from "lucide-react";
import { useMemo, useState } from "react";
import { AccountPageShell } from "@/components/account-page-shell";
const offers = [
  { title: "São Paulo → Córdoba", category: "Flights", description: "Direct flight · Economy · VuelaYa", price: "R$742.00", typical: "R$1,120.00", saving: "33% below typical", image: "/dashboard/flight-opportunity.jpg", href: "/lojas-conectadas/vuelaya", icon: PlaneIcon },
  { title: "Mexico City → Bogotá", category: "Flights", description: "Round-trip estimate · Economy · VuelaYa", price: "R$2,300.00", typical: "R$2,780.00", saving: "17% below typical", image: "/dashboard/flight-opportunity.jpg", href: "/lojas-conectadas/vuelaya", icon: PlaneIcon },
  { title: "Buenos Aires → São Paulo", category: "Flights", description: "Direct flight · Economy · VuelaYa", price: "R$1,850.00", typical: "R$2,240.00", saving: "17% below typical", image: "/dashboard/flight-opportunity.jpg", href: "/lojas-conectadas/vuelaya", icon: PlaneIcon },
];
export function OpportunitiesPage() { const [category, setCategory] = useState("All"); const [query, setQuery] = useState(""); const results = useMemo(() => offers.filter((offer) => (category === "All" || offer.category === category) && offer.title.toLowerCase().includes(query.toLowerCase())), [category, query]); return <AccountPageShell activePage="opportunities"><div className="border-b pb-8"><p className="font-mono text-[10px] tracking-[.14em] text-muted-foreground uppercase">JaguaryAI / opportunities</p><h1 className="mt-3 text-5xl [font-family:var(--font-serif)]">What your agents found</h1><p className="mt-4 text-muted-foreground">Review opportunities, compare them with typical prices, and decide what happens next.</p></div><div className="mt-7 flex flex-wrap gap-2">{["All", "Flights", "Computers"].map((filter) => <button className={`rounded-full px-3 py-1.5 text-sm ${category === filter ? "bg-[#151c30] text-white" : "border"}`} key={filter} onClick={() => setCategory(filter)} type="button">{filter}</button>)}<label className="ml-auto inline-flex items-center gap-2 rounded-md border px-3 py-1.5 text-sm"><SearchIcon className="size-4" /><input className="w-32 outline-none" onChange={(event) => setQuery(event.target.value)} placeholder="Search" value={query} /></label></div><div className="mt-5 grid gap-5">{results.map(({ title, category: offerCategory, description, price, typical, saving, image, href, icon: Icon }) => <article className="grid gap-5 rounded-xl border bg-card p-5 shadow-xs md:grid-cols-[220px_1fr_auto] md:items-center" key={title}><img alt={`${title} opportunity`} className="h-44 w-full rounded-lg object-cover md:h-32 md:w-[220px]" src={image} /><div><span className="inline-flex items-center gap-1 rounded bg-[#eef0ff] px-2 py-1 text-[10px] text-[#3157fa]"><Icon className="size-3" />{offerCategory}</span><h2 className="mt-3 text-2xl [font-family:var(--font-serif)]">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p><p className="mt-4 text-sm"><CheckCircle2Icon className="mr-1 inline size-4 text-emerald-700" />Recommended because it is {saving.toLowerCase()}.</p></div><div className="text-left md:text-right"><strong className="text-2xl text-emerald-700">{price}</strong><p className="mt-1 text-xs text-muted-foreground">Typical: {typical}</p><p className="mt-1 text-xs text-emerald-700">{saving}</p><Link className="mt-5 inline-flex rounded-md bg-[#151c30] px-4 py-2 text-sm text-white" href={href}>Review offer</Link></div></article>)}{results.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No opportunities match these filters.</div> : null}</div></AccountPageShell>; }
