"use client";
import Link from "next/link";
import { BotIcon, CheckIcon, CircleDollarSignIcon, Clock3Icon, LockKeyholeIcon, PlaneIcon, ShieldCheckIcon, ShoppingBagIcon } from "lucide-react";
import { useState } from "react";
import { AccountPageShell } from "@/components/account-page-shell";
function Intro({ title, copy }: { title: string; copy: string }) { return <div className="border-b pb-8"><p className="font-mono text-[10px] tracking-[.14em] text-muted-foreground uppercase">JaguaryAI / workspace</p><h1 className="mt-3 text-5xl [font-family:var(--font-serif)]">{title}</h1><p className="mt-4 max-w-2xl text-muted-foreground">{copy}</p></div>; }
const agents = [{ name: "VuelaYa", detail: "Monitoring flights", icon: PlaneIcon, color: "bg-[#5967d9]", link: "/lojas-conectadas/vuelaya" }, { name: "MercadoFlux Agent", detail: "Tracking marketplace prices", icon: ShoppingBagIcon, color: "bg-[#ffbe36]", link: "/lojas-conectadas/mercado-flux" }];
export function AgentsPage() { return <AccountPageShell activePage="dashboard"><Intro title="Your agents" copy="Each agent can find offers, but only acts within the permissions you approve." /><div className="mt-8 grid gap-4 md:grid-cols-2">{agents.map(({ name, detail, icon: Icon, color, link }) => <article className="rounded-xl border bg-card p-6 shadow-xs" key={name}><span className={`grid size-12 place-items-center rounded-xl text-white ${color}`}><Icon className="size-6" /></span><h2 className="mt-5 text-2xl [font-family:var(--font-serif)]">{name}</h2><p className="mt-2 text-sm text-muted-foreground">{detail}</p><span className="mt-4 inline-block rounded-full bg-emerald-950/8 px-2 py-1 text-[10px] text-emerald-800">ACTIVE</span><Link className="mt-6 block text-sm text-[#3157fa]" href={link}>Open connected store →</Link></article>)}</div></AccountPageShell>; }
const opportunities = [{ title: "São Paulo → Córdoba", description: "Direct flight · Economy", price: "R$742.00", store: "VuelaYa", href: "/lojas-conectadas/vuelaya" }, { title: "MacBook Pro 14”", description: "13% below typical price", price: "R$11,490.00", store: "MercadoFlux", href: "/lojas-conectadas/mercado-flux" }];
export function OpportunitiesPage() { return <AccountPageShell activePage="dashboard"><Intro title="Opportunities" copy="Offers found by your agents. Reviewing an offer never creates a purchase by itself." /><div className="mt-8 grid gap-4">{opportunities.map((offer) => <article className="flex flex-wrap items-center gap-5 rounded-xl border bg-card p-6 shadow-xs" key={offer.title}><CircleDollarSignIcon className="size-10 text-[#3157fa]" /><div className="min-w-48 flex-1"><h2 className="text-xl [font-family:var(--font-serif)]">{offer.title}</h2><p className="mt-1 text-sm text-muted-foreground">{offer.description} · {offer.store}</p></div><strong className="text-xl text-emerald-700">{offer.price}</strong><Link className="rounded-md bg-[#151c30] px-4 py-2 text-sm text-white" href={offer.href}>Review offer</Link></article>)}</div></AccountPageShell>; }
export function ApprovalCenterPage() { const [approved, setApproved] = useState(false); return <AccountPageShell activePage="dashboard"><Intro title="Approval Center" copy="Nothing is purchased until you explicitly approve the exact terms shown here." />{approved ? <div className="mt-8 rounded-xl border border-emerald-200 bg-emerald-50 p-6"><CheckIcon className="inline size-5 text-emerald-700" /> <strong className="ml-2">Approval recorded</strong><p className="mt-2 text-sm">The VuelaYa flight may now proceed within its approved limit.</p></div> : <article className="mt-8 rounded-xl border bg-card p-6 shadow-xs"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-xl bg-[#5967d9] text-white"><PlaneIcon /></span><div><h2 className="text-2xl [font-family:var(--font-serif)]">Flight requires your approval</h2><p className="mt-2 text-sm text-muted-foreground">São Paulo → Córdoba · Economy · VuelaYa</p></div></div><strong className="mt-6 block text-3xl">R$879.00</strong><p className="mt-1 text-sm text-muted-foreground">Your limit: R$900.00</p><div className="mt-6 flex gap-3"><button className="rounded-md bg-[#151c30] px-5 py-2 text-sm text-white" onClick={() => setApproved(true)}>Approve</button><button className="rounded-md border px-5 py-2 text-sm">Decline</button></div></article>}</AccountPageShell>; }
export function TrustCenterPage() { const protections = [["Purchase approval", "Always required"], ["Spending limits", "You’re in control"], ["Payment protection", "Your data is safe"], ["Auditability", "Everything is logged"]]; return <AccountPageShell activePage="audit"><Intro title="Trust Center" copy="Every agent action is constrained, reviewable, and connected to an auditable decision trail." /><div className="mt-8 grid gap-4 md:grid-cols-2">{protections.map(([title, detail]) => <article className="rounded-xl border bg-card p-6 shadow-xs" key={title}><ShieldCheckIcon className="size-6 text-[#3157fa]" /><h2 className="mt-4 text-xl [font-family:var(--font-serif)]">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{detail}</p></article>)}</div><Link className="mt-8 inline-flex items-center gap-2 rounded-md bg-[#151c30] px-5 py-2 text-sm text-white" href="/trilha-de-auditoria"><LockKeyholeIcon className="size-4" />Open audit trail</Link></AccountPageShell>; }
