import Link from "next/link";
import { ArrowLeftIcon, CalendarIcon, CheckCircle2Icon, PlaneTakeoffIcon, ShieldCheckIcon } from "lucide-react";

const flights = {
  "vy-471": { from: "São Paulo", to: "Córdoba", date: "Sep 18, 2026", time: "10:00", duration: "3h 05m", price: 890, stops: "Nonstop" },
  "vy-182": { from: "São Paulo", to: "Buenos Aires", date: "Sep 22, 2026", time: "08:40", duration: "3h 15m", price: 1040, stops: "Nonstop" },
  "vy-822": { from: "Mexico City", to: "Bogotá", date: "Sep 26, 2026", time: "13:10", duration: "4h 35m", price: 1280, stops: "1 stop" },
} as const;

export default async function FlightPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const flight = flights[id as keyof typeof flights];
  if (!flight) return <main className="grid min-h-dvh place-items-center bg-[#f8f6f1] p-6 text-center"><div><h1 className="text-3xl [font-family:var(--font-display)]">Flight not found</h1><Link className="mt-5 inline-flex text-[#334de8] underline" href="/lojas-conectadas/vuelaya">Back to search</Link></div></main>;
  return <main className="min-h-dvh bg-[#f8f6f1] px-5 py-7 text-[#182234] md:px-8"><div className="mx-auto max-w-3xl"><Link className="inline-flex items-center gap-2 text-sm font-medium hover:text-[#334de8]" href="/lojas-conectadas/vuelaya"><ArrowLeftIcon className="size-4" />Change search</Link><p className="mt-10 font-mono text-[10px] tracking-[.14em] text-[#566070] uppercase">VuelaYa · offer review</p><h1 className="mt-3 text-5xl leading-none [font-family:var(--font-display)]">Your journey starts here.</h1><article className="mt-8 rounded-2xl border bg-white p-6 shadow-lg"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-[#566070]">Selected route</p><h2 className="mt-2 text-3xl [font-family:var(--font-display)]">{flight.from} <span className="text-[#334de8]">→</span> {flight.to}</h2></div><span className="grid size-11 place-items-center rounded-full bg-[#334de8] text-white"><PlaneTakeoffIcon className="size-5" /></span></div><dl className="mt-7 grid gap-4 border-y py-5 text-sm sm:grid-cols-3"><div><dt className="text-[#566070]">Departure</dt><dd className="mt-1 font-medium"><CalendarIcon className="mr-1 inline size-4" />{flight.date}, {flight.time}</dd></div><div><dt className="text-[#566070]">Duration</dt><dd className="mt-1 font-medium">{flight.duration}</dd></div><div><dt className="text-[#566070]">Itinerary</dt><dd className="mt-1 font-medium">{flight.stops}</dd></div></dl><div className="mt-6 flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm text-[#566070]">Total per passenger</p><strong className="text-3xl">R$ {flight.price.toLocaleString("en-US")}</strong></div><Link className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#334de8] px-5 text-sm font-medium text-white hover:bg-[#263cc4]" href={`/demo?offer=${id}`}><CheckCircle2Icon className="size-4" />Continue with Jaguary</Link></div></article><p className="mt-5 flex items-center gap-2 text-xs leading-5 text-[#566070]"><ShieldCheckIcon className="size-4 text-[#334de8]" />You will continue to a new conversation; a purchase can only happen after your explicit approval.</p></div></main>;
}
