export const RAIL_STATIONS = [
  {
    id: "human",
    index: "01",
    label: "Human",
    verb: "Defines",
    eyebrow: "Intent starts here",
    copy: "Marta defines the trip, the ceiling, and the moment an agent may act. Authority starts with her — never with the model.",
    pending: false,
  },
  {
    id: "mandate",
    index: "02",
    label: "Mandate",
    verb: "Limits",
    eyebrow: "Authority becomes inspectable",
    copy: "Merchant, amount, validity, and one-use scope become an immutable, revocable letter before any economic action.",
    pending: false,
  },
  {
    id: "agent",
    index: "03",
    label: "Agent",
    verb: "Proposes",
    eyebrow: "The model is not the authority",
    copy: "TravelBot can search and propose a purchase, but it cannot create ALLOW, resolve a payment credential, or leave the active mandate.",
    pending: false,
  },
  {
    id: "checkout",
    index: "04",
    label: "Checkout",
    verb: "Fixes",
    eyebrow: "Commercial truth comes from the merchant",
    copy: "VuelaYa signs the exact route, price, fulfillment, and expiry. Neither TravelBot nor Jaguary authors the commercial terms.",
    pending: false,
  },
  {
    id: "verify",
    index: "05",
    label: "Bound Verify",
    verb: "Decides",
    eyebrow: "Deterministic enforcement",
    copy: "Bound checks identity, signatures, checkout binding, scope, limits, nonce, replay, and current mandate state before reserving a decision.",
    pending: false,
  },
  {
    id: "payment",
    index: "06",
    label: "Payment",
    verb: "Waits",
    eyebrow: "Money stays beyond the boundary",
    copy: "Only a transactionally reserved ALLOW can reach the payment executor. Revoke or mismatch cuts the rail before money moves.",
    pending: true,
  },
] as const;

export type RailStation = (typeof RAIL_STATIONS)[number];
